// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 30/04/2024 17:17:26
const configMerger = require("/Users/kennyramin/Documents/Parcoursup/front/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/kennyramin/Documents/Parcoursup/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kennyramin/Documents/Parcoursup/front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kennyramin/Documents/Parcoursup/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kennyramin/Documents/Parcoursup/front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kennyramin/Documents/Parcoursup/front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kennyramin/Documents/Parcoursup/front/plugins/**/*.{js,ts,mjs}","/Users/kennyramin/Documents/Parcoursup/front/composables/**/*.{js,ts,mjs}","/Users/kennyramin/Documents/Parcoursup/front/utils/**/*.{js,ts,mjs}","/Users/kennyramin/Documents/Parcoursup/front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kennyramin/Documents/Parcoursup/front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kennyramin/Documents/Parcoursup/front/app.config.{js,ts,mjs}"] }));

module.exports = config
